== Im Dschungel der Such-APIs

*Folgende Anforderung liegt auf dem Tisch:*

Über ein Frontend sollen Entities in einer Liste seitenweise angezeigt werden können.
Die Darstellung soll sortierbar sein. Außerdem muss nach einigen Attributen gefiltert werden können.

Hierzu soll ein Adapter erstellt werden, das die Daten von einem oder mehreren Backend-Systemen abruft
und dem Frontend bereitstellt.

Dabei soll natürlich darauf geachtet werden, dass
notwendige Zugriffe auf die genutzte(n) APIs so gering und klein wie nötig gehalten werden,
Sortierung und Paging über die gesamte Ergebnisliste hinweg konsistent sind und
der Algorithmus performant und ressourcenschonend arbeitet

*Nach Sichtung der zur Verfügung stehenden APIs stellt sich Ernüchterung ein.*

Die APIs können bei weitem nicht das, was gebraucht wird:

Es fehlen wichtige Filtermöglichkeiten, das seitenweise Abrufen funktioniert über eine
Scroll-ID statt über eine Seitennummer, und / oder für manche Abfragen müssen mehrere
Aufrufe gemacht und die Ergebnisse zusammengeführt werden.
