[[custom-filters]]
== Nicht unterstützte Filter

Wenn Daten über die Möglichkeiten einer API hinaus gefiltert werden sollen,
ist eine 1:1-Zuordnung von abgerufenen Seiten und Seiten der Ergebnisliste
nicht mehr möglich. Es müssen u.U. weitere Daten nachgeladen weren, um eine
Ergebnisseite zu füllen.

image::images/PagingWithFilter.svg[]

Damit zum Laden einer bestimmten Seite nicht alle vorherigen Seiten aus dem Backend
nachgeladen werden müssen, sollten die vom Adapter erzeugten Seiten gecached werden.

* Die Vorhaltedauer und Größe des Caches muss abhängig von der konkreten Anwendung gewählt werden.
* Sollte eine Seite nicht mehr im Cache liegen, müssen ausgehend von der letzten
  vorherigen Seite im Cache alle Inhalte erneut geladen werden. Deswegen darf der Cache nicht zu klein gewählt werden.
* Mit einem zweiten, parallel gepflegten Cache, welcher Seite und Index der Ausgangsdaten
  einer Seite enthält, können deutlich mehr Seiten im Speicher gehalten
  und damit das Nachladen von Daten wesentlich reduziert werden.

image::images/PagingWithFilterAndCache.svg[]
